# Generated by Django 3.1.7 on 2021-03-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('slug', models.CharField(default='xAua1', max_length=15, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='cutter.shorturl')),
            ],
        ),
    ]
