# Generated by Django 3.1.7 on 2021-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='name',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.CharField(default='dcXud', max_length=15, primary_key=True, serialize=False),
        ),
    ]
